name: Release

on:
  release:
    types: [published, prereleased]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@f4ca6f671bd429efb108c0f2fa0ae8af0215986c  # master 2026-06-22

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}

      - name: Create zip
        run: |
          cd custom_components/polleninformation
          zip polleninformation.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@14569a2d348419d066e34e5dfa65071ecd30b64b  # v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/polleninformation/polleninformation.zip
          asset_name: polleninformation.zip
          tag: ${{ github.ref_name }}
          overwrite: true
